apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: go-zqvavrtc
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtap_qe/go-zqvavrtc:53d72c8b7eb8449f9c9898531b52a374289d288b@sha256:929992d5ccdaa709c0cb7dd8d2fe561555608b3363a621a7bb3b166d04fe7541
          name: container-image
